### ISSUE TITLE
Please delete or rename old "Test" module

### ISSUE THREAD

**Issue by thewoolleyman** [mgold/elm-random-pcg#12]
The file https://github.com/mgold/elm-random-pcg/blob/master/test/old-0.16/independentSeed.elm declares a module named "Test", which interferes with the standard "Test" module declared in https://github.com/elm-community/elm-test/blob/master/src/Test.elm

My editor (intellij) kept finding the wrong one and showing bogus syntax errors.

Thanks!
-- Chad

**Comment by mgold** [comment]
Released in 3.0.4. Seems like a silly thing to do a release for, but hey if someone is troubled enough to open an issue...

**Comment by thewoolleyman** [comment]
Thanks :)
