### ISSUE TITLE
Question on creating a cryptographically secure version of Random.Pcg

### ISSUE THREAD

**Issue by Zinggi** [mgold/elm-random-pcg#18]
Hi @mgold 

This is not really an issue, so feel free to close immediately. Instead, I'd like to get your input on the following:  

For an application I'm working on at the moment, I need to generate passwords according to some user defined criteria. (E.g. no special characters, but at least one number).    
Doing that with this API is amazingly nice!    
However, generating passwords should happen in a cryptographically secure way, so I'd like to switch to a cryptographically secure version.    

My understanding of what changes I'd have to make in order to get the same API, but in a secure way are the following:    
 * Let the seed be an array of bytes of configurable length (probably an `Array Int`)
 * Change the [next](https://github.com/mgold/elm-random-pcg/blob/master/src/Random/Pcg.elm#L165) function to an algorithm like [this one](https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant)
 * Change the [peel](https://github.com/mgold/elm-random-pcg/blob/master/src/Random/Pcg.elm#L175) function to work with the new seed.

Anything else I missed?

Thanks for your time, I'd greatly appreciate your input.

P.S:
Currently I can already seed Random.Pcg with (hopefully) true randomness from `window.crypto.getRandomValues(..)`, but then I can only use 53bit (or is it 32bit?) of initial randomness.
Additionally, with the current implementation, knowing a part of the password might allow a sophisticated attacker to guess the whole password. Or maybe not, as it is [not yet known how predictable PCG actually is](http://www.pcg-random.org/predictability.html).

**Comment by mgold** [comment]
Neither this library not myself wants to be in the business of cryptographically secure PRNGs. As you say, the cryptographic strength of PCG is not known. I think seeding PCG with a cryptographic seed, as you are doing, is "pretty secure". If it's not secure enough (you're call, not mine) you should follow best practices in JS and pass in the whole password through a port.

> 53bit (or is it 32bit?) 

32 bits.

**Comment by Zinggi** [comment]
Thanks for your reply.
I think there was a misunderstanding of my intentions, I wasn't too clear about that, sorry.

My intentions are **not** to make this library cryptographically secure, the library is perfectly fine as it is now and very useful for a large range of use cases.

I intended to create a **fork** that would provide the same API, but with a different RNG plus a larger seed.

However, after doing some more research, it seems like PCG is actually what I want, except that I'd need more bits of initial randomness for my purposes.
Turns out predictability isn't an important property for my use case, as I use a different initial seed for every password.

**Comment by mgold** [comment]
Okay, best of luck with your fork. Just know that as soon as you claim cryptographic security, you open yourself up to a intense scrutiny by people using a lot of math :P

**Comment by Zinggi** [comment]
Thanks!

> Just know that as soon as you claim cryptographic security, you open yourself up to a intense scrutiny by people using a lot of math :P

Which is exactly what you want if you want to provide a crypto library ;)

But after realizing I don't really need unpredictability for my application, I'm just going to create a fork with a larger internal state, e.g. `pcg32_k64` should be large enough.

**Comment by mgold** [comment]
Earlier versions of this library used the 64-bit version. It proved to be very slow without native 64-bit integers.

**Comment by Zinggi** [comment]
Thanks for the warning.   
I only need a couple of hundreds random numbers, so I'm not too concerned about performance.

**Comment by Zinggi** [comment]
For your information, I published my fork.   
It implements the [PCG-Extended](http://package.elm-lang.org/packages/Zinggi/elm-random-pcg-extended/latest/) variant.   
This allows me to seed the generator with an arbitrary large number of bits and an arbitrary large period.

Thanks for all the work you've put into `elm-random-pcg`, you made this possible 😃

**Comment by mgold** [comment]
Thanks for the clear explanation of the fork in the README :)

**Comment by Zinggi** [comment]
Yeah, I hate when I see a fork of some popular package on [package.elm-lang.org](http://package.elm-lang.org) that doesn't explain why it exists :)
