### ISSUE TITLE
Add support for using generated value for multiple `Cmd msg`s

### ISSUE THREAD

**Issue by ahstro** [mgold/elm-random-pcg#19]
It would be lovely to be able to use the generated value for multiple `Cmd msg`, like this:

```elm
Random.generateMultiple
    (\id ->
        [ id
            |> (++) "/view/"
            |> Navigation.newUrl
        , Port.DoThingWithId id
        ]
    )
    idGenerator
```

This seems to be hard to accomplish with how `Random.generate` is built (using `Task`s), but thought it'd be worth to create an issue regardless.

From what I can tell, the easiest way to do this currently is with something like this, which feels a bit bloated:

```elm
Random.generateMultiple
    DoThingWithId
    idGenerator

...

type Msg = DoThingWithId Id

update msg model =
    case msg of
        DoThingWithId id -> 
            ( model,
            , Cmd.batch
                [ id
                    |> (++) "/view/"
                    |> Navigation.newUrl
                , Port.DoThingWithId id
                ]
            )
```

**Comment by mgold** [comment]
I don't think this is going to happen, since I don't want to tie this library to Cmd more than is necessary to have API parity with core.

What you could do is (haven't tried it with the compiler, might have a small mistake)

```elm
generateTask : Random.Generator a -> Task e a
generateTask generator =
   Time.now  
   |> Task.map (round >> initialSeed >> Random.step generator >> Tuple.first)
```

This will give you a Task rather than a Cmd that you can then use with `Task.andThen` to chain other Tasks together. Then you convert the task to a command at the end.

**Comment by ahstro** [comment]
Thanks, that looks like a good solution. Any reason that is not in this package? Seems like it could be useful for this exact situation, and probably other ones I can't think of.

**Comment by mgold** [comment]
This package mimics core's API, which used Cmd. Why, I don't know, other than to guess avoiding handling an error case that is possible with tasks generally but not psuedorandomness. And it's never come up before now.
