### ISSUE TITLE
RFC: support generate in a less-than-ideal way?

### ISSUE THREAD

**Issue by mgold** [mgold/elm-random-pcg#3]
Because of restrictions on effects modules, 2.0.0 does not include `generate : (a -> msg) -> Generator a -> Cmd msg`. For core, the seed is initialized to the current time (which isn't great, and is worse for core's RNG, but it's not awful for PNG). Then the runtime maintains the current seed. But [without permission](https://github.com/elm-lang/package.elm-lang.org/issues/168), I can't do the same. Instead I'd have to [generate 64 bits from core's RNG, use them to initialize a seed,](https://github.com/mgold/elm-random-pcg/commit/772e24bf35391b93370f989abac946608ca1998e) and then throw that seed away once the generator has been run on it. Between using an inferior RNG for seeding and calling `initialSeed2` many times, the statistical robustness of psuedo-random values will be compromised (though I'd love test data as to by how much).

That said, the API goal for this library has always been "drop in replacement for core". That is, take any valid Elm program using core's Random module, replace `import Random` with `import Random.Pcg as Random`, and the program still compiles and generates random values.

**I am seeking feedback from users of the library** as to whether you prefer the complete API or not compromising on statistical robustness.

**Comment by nphollon** [comment]
Would expanding the API compromise the performance of the existing library?

I think it would be great to offer a replacement `generate` as long as users can continue to use `step` if they need better randomness. The documentation would just need to make it clear that if you want the most robust output, you can't use `generate`.

**Comment by mgold** [comment]
That seems reasonable.

Also, this might be made moot because Evan has asked for me to send a PR to add the PCG implementation to core. I haven't had time to do it, and he might not accept it even though we talked about it in person, but I thought I'd mention it.

**Comment by mgold** [comment]
`generate` was added in 3.0.0, with a note about its tradeoffs vs. `step`.
